name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: <Your-Azure-Function-App-Name>
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}